export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CHANGE_MODE = 'CHANGE_MODE';
export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL"
export const REGISTRATION_FAIL = "REGISTRATION_FAIL"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"